// Generated by CoffeeScript 2.2.2
// cube.coffee
// coffee -> ES5
// coffee (decafeinate) -> ES6

// Create 
var cube, cubeList, i, len, list, num;

cube = function(num) {
  return Math.pow(num, 3);
};

// Collect
list = [1, 2, 3, 4, 5];

// Store
console.log(cubeList = [
  (function() {
    var i,
  len,
  results;
    results = [];
    for (i = 0, len = list.length; i < len; i++) {
      num = list[i];
      results.push(cube(num));
    }
    return results;
  })()
]);

for (i = 0, len = list.length; i < len; i++) {
  num = list[i];
  // Iterate
  console.log(cube(num));
}
