// Generated by CoffeeScript 2.2.2
(function() {
  // hello.coffee
  var boundFn, normalFn, show;

  show = console.log;

  show('Hello World! Function calls: simple/indexed/bound');

  normalFn = function() {
    return show('Normal function - thin arrow Hello World!');
  };

  boundFn = () => {
    return show('Bound function - fat arrow  Hello World!');
  };

  normalFn();

  boundFn();

}).call(this);
