// Generated by CoffeeScript 1.12.4

/* comprehensions.coffee */


/*
 * Array pattern
for student in ['Ram', 'Mohammed', 'John']
  console.log student
  
 * Object pattern
for key, value of { name: 'Mohammed', age: 24, phone: '984-820-2388', active: true }
  console.log key + '::' + value
 */

(function() {
  var student, students;

  students = [
    {
      name: 'Mohammed',
      age: 24,
      phone: '984-820-2388'
    }, {
      name: 'Ram',
      age: 25,
      phone: '980-334-9942'
    }, {
      name: 'John',
      age: 24,
      phone: '987-990-7788'
    }
  ];

  students = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = students.length; i < len; i++) {
      student = students[i];
      results.push(student.name);
    }
    return results;
  })();

  console.log(students);

  console.log('students: ' + students);


  /*
  names = (student.name for student in students)
  console.log 'names: ' +  names
  
  ages = (student.age for student in students)
  console.log 'ages: ' + ages
  
  phones = (student.phone for student in students)
  console.log 'phones: ' + phones
   */

}).call(this);
