// Generated by CoffeeScript 1.12.4

/* throws.js */

(function() {
  var myFunc;

  myFunc = function() {
    var a, b, c, e;
    a = 100;
    b = 0;
    try {
      if (b === 0) {
        throw "Divided by zero error";
      } else {
        return c = a / b;
      }
    } catch (error) {
      e = error;
      return console.log(e);
    }
  };

  myFunc();

}).call(this);
