// Generated by CoffeeScript 2.2.2
// function-be.coffee
var scope;

scope = 'Now Coffee compiler generating function-be.js (Node.js) function...';

console.log(scope);

exports.square = function(x) {
  return x * x;
};

// eof
