// Generated by CoffeeScript 2.2.2
// function-fe.coffee
var scope;

scope = 'Now Coffee compiler generating function-fe.js (ES5) function...';

console.log(scope);

global.foo = function() {
  return "bar";
};

// eof
