// Generated by CoffeeScript 2.2.2
// hello.coffee
var callback, normal, show;

show = console.log;

show('Hello World!');

normal = function() {
  return show('Normal Hello World!');
};

callback = () => {
  return show('Callback Hello World!');
};

normal();

callback();
