// Generated by CoffeeScript 2.2.2
var add, c, divide, message, multiply, remainder, show, subtract;

message = "Sum of two numbers is ";

show = console.log;

// @ abstract
add = (a, b) => {
  var c;
  return c = a + b;
};

subtract = function(a = 1, b = 1) {
  var c;
  return c = a - b;
};

multiply = function(a = 1, b = 1) {
  var c;
  return c = a * b;
};

divide = function(a = 1, b = 1) {
  var c;
  return c = a / b;
};

remainder = function(a = 1, b = 1) {
  var c;
  return c = a % b;
};

// @ implement
c = add(1, 2);

show(message + c);

c = subtract(1, 2);

show(message + c);

c = multiply(1, 2);

show(message + c);

c = divide(1, 2);

show(message + c);

c = remainder(1, 2);

show(message + c);
