// Generated by CoffeeScript 2.2.2
var band, bands, show;

show = console.log;

band = function(first, second, ...others) {
  var i, len, member, ref, results;
  this.first = first;
  this.second = second;
  this.others = others;
  show("First: " + this.first);
  show("Second: " + this.second);
  show("Others: " + this.others);
  ref = this.others;
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    member = ref[i];
    results.push(show("Players: " + member));
  }
  return results;
};

show('___ The Beatles ___');

band('John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Star');

bands = ['John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Star'];

show('___ The Musicians ___');

band(...bands);
