// Generated by CoffeeScript 2.2.2
(function() {
  // ranges.coffee
  // To store a sequence of number values in an array

  //numbers = [0..9] # include the end value
  //numbers = [0...9 # exclude the end value
  // using ranges with variables
  //start = 0
  //end = 9
  //numbers = [start..end]
  //console.log "The contains of the range are: " + numbers

  // ranges with arrays
  var data, i, len, number, numbers, ref, str, strnew,
    splice = [].splice;

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  data = [0, 1, 2, 3, 4, 5];

  console.log("The contains of the range are: " + data);

  // using negative value
  data = numbers.slice(-3);

  console.log("The contains of the range are: " + data);

  // extracting the whole array
  console.log("Total elements of the array: " + numbers.slice(0));

  // replacing the elements of an array
  splice.apply(numbers, [2, 5].concat(ref = [13, 14, 15, 16, 17])), ref;

  console.log("New array: " + numbers);

  // ranges with strings
  str = "Welcome to CoffeeScript";

  strnew = str.slice(0, 8);

  console.log(strnew);

  // comprehension (iteration) over ranges
  numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  console.log("The elements of the range are:");

// increment by 2-step
  for (i = 0, len = numbers.length; i < len; i += 2) {
    number = numbers[i];
    console.log(number);
  }

  
// Basically destructiion assigments (pattern matching for Sequence object rather than Count object

}).call(this);
