// Generated by CoffeeScript 2.2.2
var band, bands, show,
  splice = [].splice;

show = console.log;

band = function(first, second, ...others) {
  var last, ref;
  ref = others, [...others] = ref, [last] = splice.call(others, -1);
  this.first = first;
  this.second = second;
  this.others = others;
  this.last = last;
  show("First: " + this.first);
  show("Second: " + this.second);
  show("Others: " + this.others);
  return show("Last: " + this.last);
};

show('___ The Beatles ___');

band('John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Star');

bands = ['John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Star'];

show('___ The Musicians ___');

band(...bands);
