// Generated by CoffeeScript 2.2.2
(function() {
  // Dealing with JavaScript String Prototype
  var bands, members, render, show, theBeatles,
    splice = [].splice;

  console.log("___INDIVIDUAL ACCOUNT___");

  // Function - Controller
  theBeatles = function(first, second, ...others) {
    return first + ',' + second + ',' + others;
  };

  // Scope - Model
  members = {
    a: 'John Lennon',
    b: 'Paul McCartney',
    c: 'George Harrison',
    d: 'Ringo Star',
    e: 'Eric Clapton'
  };

  // Context - View		
  console.log(theBeatles(members.a, members.b, members.c, members.d, members.e));

  console.log("___GROUP ACCOUNT___");

  show = console.log;

  render = function(first, second, ...others) {
    var last, ref;
    ref = others, [...others] = ref, [last] = splice.call(others, -1);
    show("First: " + first);
    show("Second: " + second);
    show("Others: " + others);
    return show("Last: " + last);
  };

  show('___ The Beatles ___');

  render('John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Star');

  bands = ['The Beatles', 'The Rolling Stones', 'The Eagles', 'The Beach Boys'];

  show('___ The Musicians ___');

  render(...bands);

}).call(this);
