// Generated by CoffeeScript 2.2.2
// 4.2 The Power of Prototypes
var Boy, sue;

console.log('The symbol :: is to prototype keyword');

Boy = function() {};

Boy.prototype.sing = function() {
  return console.log("Boy's sing: It ain't easy being a boy named Sue");
};

sue = new Boy();

sue.sing();

// eof
