// Generated by CoffeeScript 2.2.2
// 4. Modules and Classes
// 4.1 Modules: Splitting Up Apps
console.log('Child Module');

require("./parent");

console.log('Emergency Number is ' + emergencyNumber);

console.log(emergencyNumber === global.emergencyNumber);

// eof
