// Generated by CoffeeScript 2.2.2
// 4.1 Modules: Splitting Up Apps
console.log('Child Module');

require("./parent");

console.log('Emergency Number: ' + emergencyNumber);

console.log(emergencyNumber + ' is a emergencyNumber');

// eof
