// Generated by CoffeeScript 2.2.2
// factory.j
var requisitionStarship;

console.log('Polymorphism and Switching');

requisitionStarship = function(captain) {
  switch (captain) {
    case 'Kirt':
    case 'Picard':
    case 'Archer':
      // new Enterprise()
      return console.log('Enetprise function');
    case 'Janeway':
      // new Voyager()
      return console.log('Voyager function');
    default:
      throw new Error('Invalid starship captain');
  }
};

console.log(requisitionStarship('Stephen'));
