// Generated by CoffeeScript 2.2.2
// 4.2 The Power of Protype
var Gift, gift1, gift2;

console.log('The symbol :: is to prototype keyword');

Gift = function(name) {
  this.name = name;
  Gift.count++;
  this.day = Gift.count;
  return this.announce();
};

Gift.count = 0;

Gift.prototype.announce = function() {
  return console.log(`On day ${this.day} of Chritmas I received ${this.name}`);
};

// implement
gift1 = new Gift('a partride of a pear tree');

gift2 = new Gift('two turtle doves');

// eof
