// Generated by CoffeeScript 2.2.2
// pet.js
var Dog, Pet, dog;

console.log('Inheritance with extends');

Pet = class Pet {
  constructor() {
    this.isHungry = true;
  }

  eat() {
    return this.isHungry = false;
  }

};

Dog = class Dog extends Pet {
  eat() {
    console.log("*crunch, crunch*");
    return super.eat();
  }

  fetch() {
    console.log("Yip, yip!");
    return this.isHungry = true;
  }

};

dog = new Dog();

dog.eat();

dog.fetch();

//eof
