// Generated by CoffeeScript 2.2.2
// 4.1 Modules: Splitting Up Apps
console.log('Root Module');

global.httpCodes = {
  movedPermanently: 301,
  pageNotFound: 404,
  serverError: 500
};


//exports.global = global
// eof
