// Generated by CoffeeScript 2.2.2
// 4. Modules and Classes
// 4.1 Modules: Splitting Up Apps

// In browser environment, JavaScript doesn't care about files. No matter
// how many files you have, it just a bunch of lines. So if tow files in
// an application happen to declare global-scope variables with the SAME name,
// you will have a problem with scope.

// The solution is namespacing in JavaScript (CoffeeScript), every function has
// own namespace. A (scope) variable declared in a function never visible outside
// of that function.

// So, a common JavaScript convention is to make each file a module by wrapping
// a function, which immediately (IIFE) executed.

console.log('Root Module');

global.httpCodes = {
  movedPermanently: 301,
  pageNotFound: 404,
  serverError: 500
};


// eof
