// Generated by CoffeeScript 2.2.2
// odd.coffee
var odd;

console.log("Conditionals and Exceptions");

odd = function(num) {
  if (typeof num === 'number') {
    if (num === Math.round(num)) {
      if (num > 0) {
        return num % 2 === 1;
      } else {
        throw console.log(`${num} is not positive`);
      }
    } else {
      throw console.log(`${num} is not an integer`);
    }
  } else {
    throw console.log(`${num} is not a number`);
  }
};

odd = function(num) {
  if (typeof num !== 'number') {
    throw console.log(`${num} is not a number`);
  }
  if (num !== Math.round(num)) {
    throw console.log(`${num} is not an integer`);
  }
  if (!(num > 0)) {
    throw console.log(`${num} is not positive`);
  }
  return console.log(num % 2 === 1);
};

odd('a');

odd(1.0);

odd(-1);
