// Generated by CoffeeScript 2.2.2
// odd.coffee
/* ES5
odd = (num) ->
	if typeof num is 'number'
		if num is Math.round num
			if num > 0
				num % 2 is 1
			else
				throw console.log "#{num} is not positive"
		else
			throw console.log "#{num} is not an integer"
	else
		throw console.log "#{num} is not a number"
*/
var odd;

console.log("Conditionals and Exceptions");

odd = function(num) {
  if (typeof num !== 'number') {
    throw console.log(`${num} is not a number`);
  }
  if (num !== Math.round(num)) {
    throw console.log(`${num} is not an integer`);
  }
  if (!(num > 0)) {
    throw console.log(`${num} is not positive`);
  }
  return console.log(num % 2 === 1);
};

//odd('a');
odd(1.0);

odd(-1);
