// Generated by CoffeeScript 2.2.2
var i, len, mcFlys, name;

console.log('___ Array ___');

mcFlys = ['George', 'Lorraine', 'Marty'];

for (i = 0, len = mcFlys.length; i < len; i++) {
  name = mcFlys[i];
  console.log("JSON style set: " + name);
}

mcFlys = new Array();

mcFlys[0] = 'George';

mcFlys[1] = 'Lorraine';

mcFlys[2] = 'Marty';

//for name in mcFlys[0..1]
//console.log "POJO style set with Range: " + name

//eof
