// Generated by CoffeeScript 2.2.2
// Conditional Iteration
/*
do makeHay while do sunShines
console.log '________________'
makeHay() while sunShines()
console.log '________________'

maleHay() until susSets()

loop
	console.log 'Home'
	break if @flag is true
	console.log 'Sweet'
	@flag = true
*/
var a;

a = 0;

while (true) {
  if (++a > 999) {
    break;
  }
}

console.log(a);
