// Generated by CoffeeScript 2.2.2
// This code will run each function on obj, ignoring non-function properties:
var func, key;

for (key in obj) {
  func = obj[key];
  if (typeof func === 'function') {
    func();
  }
}
